name: Citizen Savvy
favicon: null
layout_spectrum: 0.9872842479962856
typography_spectrum: 0.6432687321212143
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.6524287573993206
  lightness: 0.850816439371556
  saturation: 0.12109901499934494
  rhythmicContrast: 0.9833237049169838
purpose: []
